solution_name = "Example solution"

run:
	@echo Running solution: $(solution_name)
	@time make run_solution

run_solution:
	@# Add command to run solution, don't include building as it is timed
	@node index.js