name: Add day

on:
  schedule: 
    - cron: '0 5 * 12 *' # Every day in December at 5am UTC (12am EST)
  workflow_dispatch:
    inputs:
      day_number:
        description: 'Day number'
        type: string
        required: false

jobs:
  add-day:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make new day folder
        run: make new day=$(date +%d)
      - name: Commit folder
        run: |
          git config --global user.name "Collin Duncan"
          git config --global user.email "3679940+cgduncan7@users.noreply.github.com"
          git add .
          git commit -m "Commit for new day"
          git push
